const INIT = 'INIT'
const SET_FORM = 'SET_FORM'
const INITMENU = 'INITMENU'
const USERINFO = 'USERINFO'
const CRUMBINFO = 'CRUMBINFO'
const RESET_START = 'RESET_START'
export {
  SET_FORM,
  INIT,
  INITMENU,
  USERINFO,
  CRUMBINFO,
  RESET_START
}
